# guardar como: fix_app.py
from pathlib import Path

def fix_app():
    base_dir = Path(".")
    
    app_lines = []
    
    # Imports
    app_lines.append("import dash")
    app_lines.append("from dash import dcc, html, Input, Output, dash_table, callback_context")
    app_lines.append("import plotly.express as px")
    app_lines.append("import plotly.graph_objects as go")
    app_lines.append("import pandas as pd")
    app_lines.append("import dash_bootstrap_components as dbc")
    app_lines.append("from pathlib import Path")
    app_lines.append("import os")
    app_lines.append("")
    
    # Carga de datos
    app_lines.append("# ==========================================")
    app_lines.append("# 1. CARGA DE DATOS")
    app_lines.append("# ==========================================")
    app_lines.append("data_path = Path(__file__).parent / 'data' / 'water_potability.csv'")
    app_lines.append("")
    app_lines.append("try:")
    app_lines.append("    df = pd.read_csv(data_path)")
    app_lines.append('    print("✓ Datos cargados correctamente")')
    app_lines.append('    print(f"Filas: {len(df)}, Columnas: {len(df.columns)}")')
    app_lines.append("except Exception as e:")
    app_lines.append('    print(f"Error al cargar datos: {e}")')
    app_lines.append("    df = pd.DataFrame({")
    app_lines.append("        'ph': [7.0, 6.5, 8.0],")
    app_lines.append("        'Hardness': [200, 150, 250],")
    app_lines.append("        'Solids': [20000, 18000, 22000],")
    app_lines.append("        'Chloramines': [7, 6, 8],")
    app_lines.append("        'Sulfate': [350, 300, 400],")
    app_lines.append("        'Conductivity': [400, 350, 450],")
    app_lines.append("        'Organic_carbon': [14, 12, 16],")
    app_lines.append("        'Trihalomethanes': [65, 55, 75],")
    app_lines.append("        'Turbidity': [4, 3, 5],")
    app_lines.append("        'Potability': [0, 1, 0]")
    app_lines.append("    })")
    app_lines.append("")
    
    # Inicializar app
    app_lines.append("# ==========================================")
    app_lines.append("# 2. INICIALIZAR APP")
    app_lines.append("# ==========================================")
    app_lines.append("app = dash.Dash(__name__,")
    app_lines.append("                external_stylesheets=[dbc.themes.BOOTSTRAP,")
    app_lines.append('                                     "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"],')
    app_lines.append("                assets_folder='assets')")
    app_lines.append("app.config.suppress_callback_exceptions = True")
    app_lines.append("server = app.server")
    app_lines.append("")
    
    # Funciones helper
    app_lines.append("# ==========================================")
    app_lines.append("# 3. COMPONENTES REUTILIZABLES")
    app_lines.append("# ==========================================")
    app_lines.append("")
    app_lines.append("def create_card(title, content, color='primary', icon=None):")
    app_lines.append('    return dbc.Card([')
    app_lines.append("        dbc.CardHeader([")
    app_lines.append('            html.H4(title, className="mb-0", style={"color": "white"}),')
    app_lines.append('        ], style={"backgroundColor": f"var(--bs-{color})", "borderRadius": "10px 10px 0 0"}),')
    app_lines.append('        dbc.CardBody(content, style={"padding": "25px"})')
    app_lines.append('    ], className="mb-4 shadow-sm", style={"borderRadius": "10px", "border": "none"})')
    app_lines.append("")
    app_lines.append("def create_stat_card(title, value, subtitle, icon, color='primary'):")
    app_lines.append("    return dbc.Col([")
    app_lines.append("        dbc.Card([")
    app_lines.append("            dbc.CardBody([")
    app_lines.append("                html.Div([")
    app_lines.append('                    html.I(className=f"fas {icon}", style={"fontSize": "2.5rem", "opacity": 0.3}),')
    app_lines.append('                ], style={"position": "absolute", "top": "20px", "right": "20px"}),')
    app_lines.append('                html.H6(title, className="text-muted mb-2"),')
    app_lines.append('                html.H3(value, className=f"text-{color} mb-2"),')
    app_lines.append('                html.P(subtitle, className="text-muted mb-0", style={"fontSize": "0.9rem"})')
    app_lines.append('            ], style={"position": "relative"})')
    app_lines.append('        ], className="border-0 shadow-sm", style={"borderRadius": "15px", "backgroundColor": "white"})')
    app_lines.append("    ], md=3, className='mb-4')")
    app_lines.append("")
    
    # TEXTOS DEFINIDOS ANTES DE USARLOS (esto es lo que faltaba)
    app_lines.append("# ==========================================")
    app_lines.append("# 4. TEXTOS DEL CONTENIDO")
    app_lines.append("# ==========================================")
    app_lines.append("")
    app_lines.append("intro_text_1 = (")
    app_lines.append('    "La calidad del agua es un factor esencial para la salud y el bienestar de las personas. "')
    app_lines.append('    "Evaluar si el agua es apta para el consumo humano requiere analizar diversas "')
    app_lines.append('    "características fisicoquímicas que influyen en su potabilidad."')
    app_lines.append(")")
    app_lines.append("")
    app_lines.append("intro_text_2 = (")
    app_lines.append('    "En este proyecto se realiza un análisis exploratorio de datos sobre muestras de agua "')
    app_lines.append('    "con el fin de identificar patrones y relaciones entre las variables. Posteriormente, "')
    app_lines.append('    "se aplicarán técnicas de aprendizaje automático para desarrollar un modelo capaz de "')
    app_lines.append('    "predecir si una muestra de agua es potable o no a partir de sus características."')
    app_lines.append(")")
    app_lines.append("")
    app_lines.append("problema_text = (")
    app_lines.append('    "La calidad del agua es un aspecto fundamental para la salud humana, ya que el consumo "')
    app_lines.append('    "de agua contaminada puede generar diversas enfermedades y afectar la calidad de vida "')
    app_lines.append('    "de la población."')
    app_lines.append(")")
    app_lines.append("")
    app_lines.append("objetivo_general_text = (")
    app_lines.append('    "Desarrollar un modelo de aprendizaje automático que permita predecir la potabilidad "')
    app_lines.append('    "del agua a partir de sus características fisicoquímicas."')
    app_lines.append(")")
    app_lines.append("")
    app_lines.append("alert_carga = (")
    app_lines.append('    "Se carga el conjunto de datos de potabilidad del agua en un DataFrame de Pandas. "')
    app_lines.append('    "Posteriormente, se visualizan las primeras filas con el fin de verificar que la "')
    app_lines.append('    "información haya sido importada correctamente."')
    app_lines.append(")")
    app_lines.append("")
    app_lines.append("alert_stats = (")
    app_lines.append('    "Las estadísticas descriptivas permiten conocer el comportamiento general de las "')
    app_lines.append('    "variables numéricas. Se observa que las características presentan diferentes rangos "')
    app_lines.append('    "y niveles de dispersión."')
    app_lines.append(")")
    app_lines.append("")
    app_lines.append("alert_potab = (")
    app_lines.append('    "La variable Potability presenta dos categorías: agua no potable y agua potable. "')
    app_lines.append('    "Se observa un desbalance moderado entre las clases."')
    app_lines.append(")")
    app_lines.append("")
    app_lines.append("alert_corr = (")
    app_lines.append('    "Ninguna variable presenta una correlación lineal fuerte con la potabilidad. "')
    app_lines.append('    "Las correlaciones son muy bajas y cercanas a cero."')
    app_lines.append(")")
    app_lines.append("")
    app_lines.append("alert_matriz = (")
    app_lines.append('    "La matriz de correlación permite visualizar las relaciones lineales entre todas "')
    app_lines.append('    "las variables."')
    app_lines.append(")")
    app_lines.append("")
    
    # Navbar
    app_lines.append("# ==========================================")
    app_lines.append("# 5. SECCIONES DE CONTENIDO")
    app_lines.append("# ==========================================")
    app_lines.append("")
    app_lines.append("navbar = dbc.NavbarSimple(")
    app_lines.append("    children=[")
    app_lines.append('        dbc.NavItem(dbc.NavLink("📋 Introducción", href="#", id="nav-intro", active=True)),')
    app_lines.append('        dbc.NavItem(dbc.NavLink("🎯 Problema", href="#", id="nav-problema")),')
    app_lines.append('        dbc.NavItem(dbc.NavLink(" Objetivos", href="#", id="nav-objetivos")),')
    app_lines.append('        dbc.NavItem(dbc.NavLink("💡 Justificación", href="#", id="nav-justificacion")),')
    app_lines.append('        dbc.NavItem(dbc.NavLink("📊 Análisis EDA", href="#", id="nav-eda")),')
    app_lines.append("    ],")
    app_lines.append('    brand="🌊 Potabilidad del Agua",')
    app_lines.append('    brand_href="#",')
    app_lines.append('    color="primary",')
    app_lines.append("    dark=True,")
    app_lines.append('    sticky="top",')
    app_lines.append('    className="shadow-sm"')
    app_lines.append(")")
    app_lines.append("")
    
    # Hero
    app_lines.append("hero_section = dbc.Container([")
    app_lines.append("    dbc.Row([")
    app_lines.append("        dbc.Col([")
    app_lines.append('            html.H1("Predicción de la Potabilidad del Agua", className="display-4 fw-bold text-white mb-3"),')
    app_lines.append('            html.P("Análisis Exploratorio de Datos y Modelado Predictivo usando Machine Learning",')
    app_lines.append('                   className="lead text-white-50"),')
    app_lines.append('            dbc.Button("Ver Análisis", id="btn-ver-analisis", color="light", size="lg", className="mt-3"),')
    app_lines.append('        ], className="text-center py-5")')
    app_lines.append('    ], className="py-5")')
    app_lines.append('], className="bg-primary", style={"borderRadius": "0 0 30px 30px", "marginBottom": "40px"})')
    app_lines.append("")
    
    # Intro
    app_lines.append("intro_section = dbc.Container([")
    app_lines.append('    create_card("1. Introducción", [')
    app_lines.append('        html.P(intro_text_1, className="lead"),')
    app_lines.append("        html.P(intro_text_2)")
    app_lines.append('    ], color="primary")')
    app_lines.append('], className="py-4")')
    app_lines.append("")
    
    # Problema
    app_lines.append("problema_section = dbc.Container([")
    app_lines.append('    create_card("2. Planteamiento del Problema", [')
    app_lines.append('        html.P(problema_text, className="mb-3"),')
    app_lines.append("        dbc.Alert([")
    app_lines.append('            html.H4("Pregunta de Investigación", className="alert-heading"),')
    app_lines.append('            html.P("¿Es posible predecir la potabilidad del agua a partir de sus características fisicoquímicas mediante el uso de modelos de aprendizaje automático?", className="mb-0")')
    app_lines.append('        ], color="warning", className="mt-4")')
    app_lines.append('    ], color="danger")')
    app_lines.append('], className="py-4")')
    app_lines.append("")
    
    # Objetivos
    app_lines.append("objetivos_section = dbc.Container([")
    app_lines.append('    create_card("3. Objetivos", [')
    app_lines.append("        dbc.Row([")
    app_lines.append("            dbc.Col([")
    app_lines.append("                dbc.Card([")
    app_lines.append('                    dbc.CardHeader(html.H5("Objetivo General", className="text-white mb-0")),')
    app_lines.append("                    dbc.CardBody([")
    app_lines.append('                        html.P(objetivo_general_text, className="mb-0")')
    app_lines.append("                    ])")
    app_lines.append('                ], className="border-0 shadow-sm mb-4")')
    app_lines.append("            ])")
    app_lines.append("        ]),")
    app_lines.append('        html.H5("Objetivos Específicos", className="mb-3"),')
    app_lines.append("        dbc.ListGroup([")
    app_lines.append('            dbc.ListGroupItem("📊 Realizar un análisis exploratorio de los datos", className="d-flex align-items-center"),')
    app_lines.append('            dbc.ListGroupItem("🔍 Identificar las variables con mayor influencia", className="d-flex align-items-center"),')
    app_lines.append('            dbc.ListGroupItem("⚙️ Preparar y transformar los datos", className="d-flex align-items-center"),')
    app_lines.append('            dbc.ListGroupItem("🤖 Entrenar y evaluar modelos de clasificación", className="d-flex align-items-center"),')
    app_lines.append('            dbc.ListGroupItem("📈 Comparar el desempeño de los modelos", className="d-flex align-items-center"),')
    app_lines.append('        ], flush=True, className="mb-3")')
    app_lines.append('    ], color="success")')
    app_lines.append('], className="py-4")')
    app_lines.append("")
    
    # Justificación
    app_lines.append("justificacion_section = dbc.Container([")
    app_lines.append('    create_card("4. Justificación", [')
    app_lines.append("        dbc.Row([")
    app_lines.append("            dbc.Col([")
    app_lines.append("                html.Div([")
    app_lines.append('                    html.I(className="fas fa-tint", style={"fontSize": "3rem", "color": "#0d6efd"}),')
    app_lines.append('                    html.H5("Importancia para la Salud", className="mt-3"),')
    app_lines.append('                    html.P("El acceso a agua potable es fundamental para la salud y la calidad de vida de la población.")')
    app_lines.append('                ], className="text-center p-3")')
    app_lines.append("            ], md=6),")
    app_lines.append("            dbc.Col([")
    app_lines.append("                html.Div([")
    app_lines.append('                    html.I(className="fas fa-chart-line", style={"fontSize": "3rem", "color": "#198754"}),')
    app_lines.append('                    html.H5("Ciencia de Datos", className="mt-3"),')
    app_lines.append('                    html.P("Aplicación de técnicas de análisis de datos y aprendizaje automático para la evaluación de calidad.")')
    app_lines.append('                ], className="text-center p-3")')
    app_lines.append("            ], md=6)")
    app_lines.append("        ])")
    app_lines.append('    ], color="info")')
    app_lines.append('], className="py-4")')
    app_lines.append("")
    
    # EDA Section
    app_lines.append("eda_section = dbc.Container([")
    app_lines.append("    dbc.Row([")
    app_lines.append('        create_stat_card("Total de Muestras", f"{len(df):,}", "Registros analizados", "fa-database", "primary"),')
    app_lines.append('        create_stat_card("Variables", f"{len(df.columns)}", "Características fisicoquímicas", "fa-sliders-h", "success"),')
    app_lines.append("        create_stat_card(\"Agua Potable\", f\"{df['Potability'].sum():,}\", f\"{100*df['Potability'].mean():.1f}% del total\", \"fa-check-circle\", \"success\"),")
    app_lines.append("        create_stat_card(\"Agua No Potable\", f\"{len(df) - df['Potability'].sum():,}\", f\"{100*(1-df['Potability'].mean()):.1f}% del total\", \"fa-times-circle\", \"danger\"),")
    app_lines.append('    ], className="mb-4"),')
    app_lines.append("")
    app_lines.append("    dbc.Row([")
    app_lines.append("        dbc.Col([")
    app_lines.append('            create_card("6.2 Cargue Inicial de los Datos", [')
    app_lines.append('                html.P("Vista previa de las primeras 5 filas del dataset:", className="mb-3"),')
    app_lines.append("                dbc.Table.from_dataframe(df.head(5), striped=True, bordered=True, hover=True, responsive=True),")
    app_lines.append('                dbc.Alert(alert_carga, color="info", className="mt-3")')
    app_lines.append('            ], color="secondary")')
    app_lines.append("        ])")
    app_lines.append('    ], className="mb-4"),')
    app_lines.append("")
    app_lines.append("    dbc.Row([")
    app_lines.append("        dbc.Col([")
    app_lines.append('            create_card("6.3 Información General del Dataset", [')
    app_lines.append("                dbc.Row([")
    app_lines.append('                    dbc.Col(html.H6(f"Total de registros: {len(df)}", className="text-primary"), md=6),')
    app_lines.append('                    dbc.Col(html.H6(f"Total de columnas: {len(df.columns)}", className="text-success"), md=6),')
    app_lines.append('                ], className="mb-3"),')
    app_lines.append('                html.P("Detalle de tipos de datos y valores no nulos:", className="mb-3"),')
    app_lines.append("                dbc.Table([")
    app_lines.append('                    html.Thead(html.Tr([html.Th("Columna"), html.Th("Tipo"), html.Th("No-Nulos"), html.Th("Nulos")])),')
    app_lines.append("                    html.Tbody([")
    app_lines.append("                        html.Tr([")
    app_lines.append("                            html.Td(col),")
    app_lines.append("                            html.Td(str(df[col].dtype)),")
    app_lines.append("                            html.Td(df[col].notna().sum()),")
    app_lines.append("                            html.Td(df[col].isna().sum())")
    app_lines.append("                        ]) for col in df.columns")
    app_lines.append("                    ])")
    app_lines.append("                ], striped=True, responsive=True),")
    app_lines.append('            ], color="info")')
    app_lines.append("        ])")
    app_lines.append('    ], className="mb-4"),')
    app_lines.append("")
    app_lines.append("    dbc.Row([")
    app_lines.append("        dbc.Col([")
    app_lines.append('            create_card("6.4 Estadísticas Descriptivas", [')
    app_lines.append("                dbc.Table.from_dataframe(")
    app_lines.append("                    df.describe().round(2).T.reset_index().rename(columns={'index': 'Variable'}),")
    app_lines.append("                    striped=True, bordered=True, hover=True, responsive=True")
    app_lines.append("                ),")
    app_lines.append('                dbc.Alert(alert_stats, color="info", className="mt-3")')
    app_lines.append('            ], color="warning")')
    app_lines.append("        ])")
    app_lines.append('    ], className="mb-4"),')
    app_lines.append("")
    app_lines.append("    dbc.Row([")
    app_lines.append("        dbc.Col([")
    app_lines.append('            create_card("6.5 Distribución de la Variable Objetivo", [')
    app_lines.append("                dcc.Graph(id='grafico-potabilidad'),")
    app_lines.append('                dbc.Alert(alert_potab, color="info", className="mt-3")')
    app_lines.append('            ], color="primary")')
    app_lines.append("        ])")
    app_lines.append('    ], className="mb-4"),')
    app_lines.append("")
    app_lines.append("    dbc.Row([")
    app_lines.append("        dbc.Col([")
    app_lines.append('            create_card("6.6 Correlación con la Potabilidad", [')
    app_lines.append("                dcc.Graph(id='grafico-correlacion-potabilidad'),")
    app_lines.append('                dbc.Alert(alert_corr, color="warning", className="mt-3")')
    app_lines.append('            ], color="secondary")')
    app_lines.append("        ])")
    app_lines.append('    ], className="mb-4"),')
    app_lines.append("")
    app_lines.append("    dbc.Row([")
    app_lines.append("        dbc.Col([")
    app_lines.append('            create_card("6.7 Matriz de Correlación Completa", [')
    app_lines.append("                dcc.Graph(id='grafico-matriz-correlacion'),")
    app_lines.append('                dbc.Alert(alert_matriz, color="info", className="mt-3")')
    app_lines.append('            ], color="dark")')
    app_lines.append("        ])")
    app_lines.append('    ], className="mb-4"),')
    app_lines.append("")
    app_lines.append("    dbc.Row([")
    app_lines.append("        dbc.Col([")
    app_lines.append('            create_card("🔍 Visualizaciones Interactivas", [')
    app_lines.append("                dbc.Row([")
    app_lines.append("                    dbc.Col([")
    app_lines.append('                        html.Label("Variable para Histograma:", className="fw-bold"),')
    app_lines.append("                        dcc.Dropdown(")
    app_lines.append("                            id='dropdown-histograma',")
    app_lines.append("                            options=[{'label': col, 'value': col} for col in df.columns if col != 'Potability'],")
    app_lines.append("                            value='ph',")
    app_lines.append("                            clearable=False,")
    app_lines.append('                            className="mb-3"')
    app_lines.append("                        )")
    app_lines.append("                    ], md=6),")
    app_lines.append("                    dbc.Col([")
    app_lines.append('                        html.Label("Tipo de Gráfico:", className="fw-bold"),')
    app_lines.append("                        dcc.Dropdown(")
    app_lines.append("                            id='dropdown-tipo-grafico',")
    app_lines.append("                            options=[")
    app_lines.append("                                {'label': '📊 Histograma', 'value': 'histogram'},")
    app_lines.append("                                {'label': '📦 Box Plot', 'value': 'box'},")
    app_lines.append("                                {'label': '🎻 Violin Plot', 'value': 'violin'}")
    app_lines.append("                            ],")
    app_lines.append("                            value='histogram',")
    app_lines.append("                            clearable=False,")
    app_lines.append('                            className="mb-3"')
    app_lines.append("                        )")
    app_lines.append("                    ], md=6)")
    app_lines.append("                ]),")
    app_lines.append("                dcc.Graph(id='grafico-interactivo', className='mb-4'),")
    app_lines.append("")
    app_lines.append("                dbc.Row([")
    app_lines.append("                    dbc.Col([")
    app_lines.append('                        html.Label("Variable Eje X:", className="fw-bold"),')
    app_lines.append("                        dcc.Dropdown(")
    app_lines.append("                            id='dropdown-x',")
    app_lines.append("                            options=[{'label': col, 'value': col} for col in df.columns if col != 'Potability'],")
    app_lines.append("                            value='ph',")
    app_lines.append("                            clearable=False,")
    app_lines.append('                            className="mb-3"')
    app_lines.append("                        )")
    app_lines.append("                    ], md=4),")
    app_lines.append("                    dbc.Col([")
    app_lines.append('                        html.Label("Variable Eje Y:", className="fw-bold"),')
    app_lines.append("                        dcc.Dropdown(")
    app_lines.append("                            id='dropdown-y',")
    app_lines.append("                            options=[{'label': col, 'value': col} for col in df.columns if col != 'Potability'],")
    app_lines.append("                            value='Chloramines',")
    app_lines.append("                            clearable=False,")
    app_lines.append('                            className="mb-3"')
    app_lines.append("                        )")
    app_lines.append("                    ], md=4),")
    app_lines.append("                    dbc.Col([")
    app_lines.append('                        html.Label("Tipo de Scatter:", className="fw-bold"),')
    app_lines.append("                        dcc.Dropdown(")
    app_lines.append("                            id='dropdown-scatter-type',")
    app_lines.append("                            options=[")
    app_lines.append("                                {'label': '⚪ Scatter Simple', 'value': 'scatter'},")
    app_lines.append("                                {'label': '📈 Con Línea de Tendencia', 'value': 'scatter+trend'}")
    app_lines.append("                            ],")
    app_lines.append("                            value='scatter',")
    app_lines.append("                            clearable=False,")
    app_lines.append('                            className="mb-3"')
    app_lines.append("                        )")
    app_lines.append("                    ], md=4)")
    app_lines.append("                ]),")
    app_lines.append("                dcc.Graph(id='grafico-scatter-interactivo')")
    app_lines.append('            ], color="primary")')
    app_lines.append("        ])")
    app_lines.append('    ], className="mb-4")')
    app_lines.append("])")
    app_lines.append("")
    
    # Footer
    app_lines.append("footer = dbc.Container([")
    app_lines.append('    html.Hr(className="my-4"),')
    app_lines.append("    dbc.Row([")
    app_lines.append("        dbc.Col([")
    app_lines.append('            html.P("© 2024 Predicción de la Potabilidad del Agua", className="text-muted mb-0"),')
    app_lines.append('            html.P("By Maria May, Andrea Padilla, Alberto Jimenez, Winston Pardo", className="text-muted mb-0")')
    app_lines.append('        ], className="text-center")')
    app_lines.append("    ])")
    app_lines.append('], className="mt-5")')
    app_lines.append("")
    
    # Layout
    app_lines.append("# ==========================================")
    app_lines.append("# 6. LAYOUT PRINCIPAL")
    app_lines.append("# ==========================================")
    app_lines.append("app.layout = html.Div([")
    app_lines.append("    navbar,")
    app_lines.append("    hero_section,")
    app_lines.append("    html.Div(id='page-content', className='pb-5'),")
    app_lines.append("    footer")
    app_lines.append('], style={"backgroundColor": "#f8f9fa", "minHeight": "100vh"})')
    app_lines.append("")
    
    # Callback navegación
    app_lines.append("# ==========================================")
    app_lines.append("# 7. CALLBACKS")
    app_lines.append("# ==========================================")
    app_lines.append("")
    app_lines.append("@app.callback(")
    app_lines.append("    Output('page-content', 'children'),")
    app_lines.append("    [Input('nav-intro', 'n_clicks'),")
    app_lines.append("     Input('nav-problema', 'n_clicks'),")
    app_lines.append("     Input('nav-objetivos', 'n_clicks'),")
    app_lines.append("     Input('nav-justificacion', 'n_clicks'),")
    app_lines.append("     Input('nav-eda', 'n_clicks'),")
    app_lines.append("     Input('btn-ver-analisis', 'n_clicks')],")
    app_lines.append("    prevent_initial_call=False")
    app_lines.append(")")
    app_lines.append("def display_page(n_intro, n_problema, n_objetivos, n_justificacion, n_eda, n_btn):")
    app_lines.append("    ctx = callback_context")
    app_lines.append("    if not ctx.triggered:")
    app_lines.append("        return intro_section")
    app_lines.append("    button_id = ctx.triggered[0]['prop_id'].split('.')[0]")
    app_lines.append("    if button_id == 'nav-problema' or button_id == 'btn-ver-analisis':")
    app_lines.append("        return problema_section")
    app_lines.append("    elif button_id == 'nav-objetivos':")
    app_lines.append("        return objetivos_section")
    app_lines.append("    elif button_id == 'nav-justificacion':")
    app_lines.append("        return justificacion_section")
    app_lines.append("    elif button_id == 'nav-eda':")
    app_lines.append("        return eda_section")
    app_lines.append("    else:")
    app_lines.append("        return intro_section")
    app_lines.append("")
    
    # Callback potabilidad
    app_lines.append("@app.callback(")
    app_lines.append("    Output('grafico-potabilidad', 'figure'),")
    app_lines.append("    Input('nav-eda', 'n_clicks')")
    app_lines.append(")")
    app_lines.append("def actualizar_potabilidad(n_clicks):")
    app_lines.append("    conteos = df['Potability'].value_counts().sort_index()")
    app_lines.append("    total = len(df)")
    app_lines.append("    fig = go.Figure(data=[")
    app_lines.append("        go.Bar(")
    app_lines.append("            x=['No Potable', 'Potable'],")
    app_lines.append("            y=conteos.values,")
    app_lines.append("            marker_color=['#8B4513', '#4169E1'],")
    app_lines.append("            text=[f'{count}<br>({100*count/total:.1f}%)' for count in conteos.values],")
    app_lines.append("            textposition='outside',")
    app_lines.append("            hovertemplate='Categoría: %{x}<br>Cantidad: %{y}<extra></extra>'")
    app_lines.append("        )")
    app_lines.append("    ])")
    app_lines.append("    fig.update_layout(")
    app_lines.append("        title='Distribución de la Potabilidad del Agua',")
    app_lines.append("        xaxis_title='Potabilidad',")
    app_lines.append("        yaxis_title='Cantidad de muestras',")
    app_lines.append("        showlegend=False,")
    app_lines.append("        template='plotly_white',")
    app_lines.append("        height=400")
    app_lines.append("    )")
    app_lines.append("    return fig")
    app_lines.append("")
    
    # Callback correlación
    app_lines.append("@app.callback(")
    app_lines.append("    Output('grafico-correlacion-potabilidad', 'figure'),")
    app_lines.append("    Input('nav-eda', 'n_clicks')")
    app_lines.append(")")
    app_lines.append("def actualizar_correlacion_potabilidad(n_clicks):")
    app_lines.append("    corr_potability = df.corr(numeric_only=True)['Potability'].drop('Potability').sort_values()")
    app_lines.append("    colors_corr = ['firebrick' if x < 0 else 'forestgreen' for x in corr_potability]")
    app_lines.append("    fig = go.Figure(data=[")
    app_lines.append("        go.Bar(")
    app_lines.append("            x=corr_potability.values,")
    app_lines.append("            y=corr_potability.index,")
    app_lines.append("            marker_color=colors_corr,")
    app_lines.append("            orientation='h',")
    app_lines.append("            text=[f'{x:.3f}' for x in corr_potability.values],")
    app_lines.append("            textposition='outside',")
    app_lines.append("            hovertemplate='Variable: %{y}<br>Correlación: %{x:.3f}<extra></extra>'")
    app_lines.append("        )")
    app_lines.append("    ])")
    app_lines.append("    fig.update_layout(")
    app_lines.append("        title='Correlación de las Variables con la Potabilidad',")
    app_lines.append("        xaxis_title='Correlación',")
    app_lines.append("        yaxis_title='Variables',")
    app_lines.append("        showlegend=False,")
    app_lines.append("        template='plotly_white',")
    app_lines.append("        height=400")
    app_lines.append("    )")
    app_lines.append("    return fig")
    app_lines.append("")
    
    # Callback matriz
    app_lines.append("@app.callback(")
    app_lines.append("    Output('grafico-matriz-correlacion', 'figure'),")
    app_lines.append("    Input('nav-eda', 'n_clicks')")
    app_lines.append(")")
    app_lines.append("def actualizar_matriz_correlacion(n_clicks):")
    app_lines.append("    corr_matrix = df.corr(numeric_only=True)")
    app_lines.append("    fig = go.Figure(data=go.Heatmap(")
    app_lines.append("        z=corr_matrix.values,")
    app_lines.append("        x=corr_matrix.columns,")
    app_lines.append("        y=corr_matrix.columns,")
    app_lines.append("        colorscale='RdBu_r',")
    app_lines.append("        zmid=0,")
    app_lines.append("        text=[[f'{corr_matrix.iloc[i, j]:.2f}' for j in range(len(corr_matrix.columns))]")
    app_lines.append("              for i in range(len(corr_matrix.columns))],")
    app_lines.append("        texttemplate='%{text}',")
    app_lines.append('        textfont={"size": 9},')
    app_lines.append("        hovertemplate='X: %{x}<br>Y: %{y}<br>Correlación: %{z:.2f}<extra></extra>'")
    app_lines.append("    ))")
    app_lines.append("    fig.update_layout(")
    app_lines.append("        title='Matriz de Correlación',")
    app_lines.append("        template='plotly_white',")
    app_lines.append("        height=600")
    app_lines.append("    )")
    app_lines.append("    return fig")
    app_lines.append("")
    
    # Callback interactivo
    app_lines.append("@app.callback(")
    app_lines.append("    Output('grafico-interactivo', 'figure'),")
    app_lines.append("    [Input('dropdown-histograma', 'value'),")
    app_lines.append("     Input('dropdown-tipo-grafico', 'value')]")
    app_lines.append(")")
    app_lines.append("def actualizar_grafico_interactivo(variable, tipo_grafico):")
    app_lines.append("    try:")
    app_lines.append("        if tipo_grafico == 'histogram':")
    app_lines.append("            fig = px.histogram(df, x=variable, color='Potability',")
    app_lines.append("                              marginal='box',")
    app_lines.append("                              title=f'Distribución de {variable} según Potabilidad',")
    app_lines.append("                              color_discrete_map={0: '#8B4513', 1: '#4169E1'},")
    app_lines.append("                              barmode='overlay',")
    app_lines.append("                              opacity=0.7)")
    app_lines.append("        elif tipo_grafico == 'box':")
    app_lines.append("            fig = px.box(df, x='Potability', y=variable,")
    app_lines.append("                        title=f'Distribución de {variable} por Potabilidad',")
    app_lines.append("                        color='Potability',")
    app_lines.append("                        color_discrete_map={0: '#8B4513', 1: '#4169E1'},")
    app_lines.append("                        points='outliers')")
    app_lines.append("            fig.update_xaxes(tickvals=[0, 1], ticktext=['No Potable', 'Potable'])")
    app_lines.append("        else:")
    app_lines.append("            fig = px.violin(df, x='Potability', y=variable,")
    app_lines.append("                           title=f'Distribución de {variable} por Potabilidad',")
    app_lines.append("                           color='Potability',")
    app_lines.append("                           color_discrete_map={0: '#8B4513', 1: '#4169E1'},")
    app_lines.append("                           box=True, points='outliers')")
    app_lines.append("            fig.update_xaxes(tickvals=[0, 1], ticktext=['No Potable', 'Potable'])")
    app_lines.append("        fig.update_layout(template='plotly_white', height=500, showlegend=True)")
    app_lines.append("        return fig")
    app_lines.append("    except Exception as e:")
    app_lines.append('        print(f"Error en gráfico interactivo: {e}")')
    app_lines.append("        import traceback")
    app_lines.append("        traceback.print_exc()")
    app_lines.append("        return go.Figure()")
    app_lines.append("")
    
    # Callback scatter
    app_lines.append("@app.callback(")
    app_lines.append("    Output('grafico-scatter-interactivo', 'figure'),")
    app_lines.append("    [Input('dropdown-x', 'value'),")
    app_lines.append("     Input('dropdown-y', 'value'),")
    app_lines.append("     Input('dropdown-scatter-type', 'value')]")
    app_lines.append(")")
    app_lines.append("def actualizar_scatter(col_x, col_y, tipo):")
    app_lines.append("    try:")
    app_lines.append("        df_clean = df[[col_x, col_y, 'Potability']].dropna()")
    app_lines.append("        if tipo == 'scatter+trend':")
    app_lines.append("            fig = px.scatter(df_clean, x=col_x, y=col_y, color='Potability',")
    app_lines.append("                            trendline='ols',")
    app_lines.append("                            title=f'Relación entre {col_x} y {col_y} (con tendencia)',")
    app_lines.append("                            color_discrete_map={0: '#8B4513', 1: '#4169E1'},")
    app_lines.append("                            opacity=0.6,")
    app_lines.append("                            trendline_color_override='red')")
    app_lines.append("        else:")
    app_lines.append("            fig = px.scatter(df_clean, x=col_x, y=col_y, color='Potability',")
    app_lines.append("                            title=f'Relación entre {col_x} y {col_y}',")
    app_lines.append("                            color_discrete_map={0: '#8B4513', 1: '#4169E1'},")
    app_lines.append("                            opacity=0.6)")
    app_lines.append("        fig.update_layout(template='plotly_white', height=500)")
    app_lines.append("        return fig")
    app_lines.append("    except Exception as e:")
    app_lines.append('        print(f"Error en scatter: {e}")')
    app_lines.append("        import traceback")
    app_lines.append("        traceback.print_exc()")
    app_lines.append("        fig = go.Figure()")
    app_lines.append('        fig.add_annotation(text=f"Error: {str(e)}", xref="paper", yref="paper",')
    app_lines.append("                          x=0.5, y=0.5, showarrow=False, font=dict(size=14, color='red'))")
    app_lines.append("        return fig")
    app_lines.append("")
    
    # Main
    app_lines.append("# ==========================================")
    app_lines.append("# 8. EJECUTAR APP")
    app_lines.append("# ==========================================")
    app_lines.append("if __name__ == '__main__':")
    app_lines.append('    print(" Iniciando servidor Dash con Bootstrap...")')
    app_lines.append('    print(" Abra http://127.0.0.1:8050 en su navegador")')
    app_lines.append("    app.run(debug=True, use_reloader=False)")
    
    with open(base_dir / "app.py", "w", encoding="utf-8") as f:
        f.write("\n".join(app_lines))
    
    print("✅ app.py corregido exitosamente")
    print("📁 Ubicación:", (base_dir / "app.py").absolute())
    print("")
    print("Ahora ejecuta:")
    print("  python app.py")

if __name__ == "__main__":
    fix_app()